### ISSUE TITLE
Crash on Raspberry Pi 1 (Raspbian) version 11 (Bullseye) when trying to start with gui

### ISSUE THREAD

**Issue by 7Saturn** [7Saturn/ef_master_server#1]
On Debian für Raspberry Pi 1 (Raspbian) version 11 (Bullseye) the server crashes if trying to start with ``--withgui`` switch. Debug messages and error message:
```
Starting EF master server ver. 0.4.1...
--debug: OK, you want it all...
 debug: Trying to start listener thread...
 debug: Starting listener thread.
 debug: StartListener
Got no interface set, listening on any available interface...
 debug: before endpoint.
 debug: after endpoint.
 debug: Entered main listener loop.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	 (No frames)


=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0xb44d1440 from 0xb6f6a040
Pkilling 0xb4e6f440 from 0xb6f6a040
Entering thread summarizer pause from 0xb6f6a040
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Finished thread summarizer pause from 0xb6f6a040.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 8377]
[New LWP 8378]
[New LWP 8379]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0xb6d714d4 in __GI___wait4 (pid=8381, stat_loc=0xbef46d88, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: Datei oder Verzeichnis nicht gefunden.
  Id   Target Id                                  Frame
* 1    Thread 0xb6f6a040 (LWP 8376) "mono"        0xb6d714d4 in __GI___wait4 (pid=8381, stat_loc=0xbef46d88, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
  2    Thread 0xb63ff440 (LWP 8377) "SGen worker" futex_wait_cancelable (private=0, expected=0, futex_word=0x447698) at ../sysdeps/nptl/futex-internal.h:186
  3    Thread 0xb4e6f440 (LWP 8378) "Finalizer"   futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323
  4    Thread 0xb44d1440 (LWP 8379) "mono"        0xb6e602ec in __libc_recvfrom (fd=6, buf=0xb4001588, len=65536, flags=0, addr=..., addrlen=0xb44d0560) at ../sysdeps/unix/sysv/linux/recvfrom.c:27

Thread 4 (Thread 0xb44d1440 (LWP 8379) "mono"):
#0  0xb6e602ec in __libc_recvfrom (fd=6, buf=0xb4001588, len=65536, flags=0, addr=..., addrlen=0xb44d0560) at ../sysdeps/unix/sysv/linux/recvfrom.c:27
#1  0x002d0e58 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0xb4e6f440 (LWP 8378) "Finalizer"):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:117
#2  0xb6e5ec80 in __new_sem_wait_slow (sem=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:285
#3  0x002c2120 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xb63ff440 (LWP 8377) "SGen worker"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x447698) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x0, cond=0x447670) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x447670, mutex=0x0) at pthread_cond_wait.c:638
#3  0x00327c84 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xb6f6a040 (LWP 8376) "mono"):
#0  0xb6d714d4 in __GI___wait4 (pid=8381, stat_loc=0xbef46d88, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0009f73c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 8376) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xb6e5c5b0):0xb6e5c5a0  bc ff ff ea 98 70 00 00 f0 4f 2d e9 14 d0 4d e2  .....p...O-...M.
0xb6e5c5b0  24 50 90 e5 a5 31 b0 e1 28 01 00 0a 00 c0 a0 e1  $P...1..(.......
0xb6e5c5c0  01 50 15 e2 20 30 bc e5 00 e0 a0 e1 80 50 a0 13  .P.. 0.......P..
0xb6e5c5d0  0a 00 00 ea 01 10 83 e3 9f 2f 9c e1 03 00 52 e1  ........./....R.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Windows.Forms.Application:EnableVisualStyles <0x00043>
	  at Masterserver:Main <0x0012b>
	  at <Module>:runtime_invoke_int_object <0x0012b>
=================================================================
```

**Comment by 7Saturn** [comment]
It is very likely, that the culprit is mono itself, judging from this thread here:

https://forums.raspberrypi.com/viewtopic.php?t=11634&start=200
