### ISSUE TITLE
Compile-Bug under Mono 6.12.0.122

### ISSUE THREAD

**Issue by 7Saturn** [7Saturn/ef_master_server#12]
When compiling the current code (v0.4.1) under Windows (_csc.exe_), everything is just fine. When compiling with latest Mono under Linux or with Github Actions (_mcs_, Mono version 6.12.0.122), the compiled binary crashes _when run under Windows_, the moment someone tries to register a server, with the following stack trace:

```
Unhandled exception: System.MissingMethodException: Method not found: "System.String[] System.String.Split(Char, System.StringSplitOptions)".
   at ServerEntry.QueryInfo()
   at ServerList.AddServer(ServerEntry new_one)
   at HeartbeatListener.StartListener(IPAddress localAddress, UInt16 listenPort)
   at Masterserver.Main(String[] args)

```
This happens right after the last debug message reads: ` debug: A new one arrived, querying data...`.

As there are no other splits in the Method `ServerEntry.QueryInfo()`, that use a char as separator, it must be the call `string[] blocks = returnData.Split('"');` which works on the string returnData.

This obviously makes no sense, as the used method is actually a built-in method (see [https://docs.microsoft.com/de-de/dotnet/api/system.string.split?view=net-6.0#system-string-split(system-char())](https://docs.microsoft.com/de-de/dotnet/api/system.string.split?view=net-6.0#system-string-split(system-char())) about it). That apparently works just fine, when compiled under Windows. So it is probably not the code. Under Linux with Mono everything works just fine as well. So currently compiling for both platforms only works properly under Windows. Linux builds are only working under Linux. Why the method `Split(Char[])` is apparently misinterpreted as `Split(Char[], StringSplitOptions)` (see [https://docs.microsoft.com/de-de/dotnet/api/system.string.split?view=net-6.0#system-string-split(system-char()-system-stringsplitoptions)](https://docs.microsoft.com/de-de/dotnet/api/system.string.split?view=net-6.0#system-string-split(system-char()-system-stringsplitoptions)) about that one) and on top of that, declared as not existing, is not quite clear. If this gets not resolved by the Mono team, then a change of this project might be in order.

**Comment by 7Saturn** [comment]
The suggested solution on the Mono Project Github page helped solving this problem. Should work just fine now under Windows and Linux alike.
